[package]
name = "tauri-plugin-positioner"
version = "0.1.0"
authors = [ "Jonas Kruckenberg" ]
description = "Helps positioning your tauri windows."
edition = "2021"
exclude = [ "/examples", "/webview-dist", "/webview-src", "node_modules" ]
license = "MIT"
repository = "https://github.com/JonasKruckenberg/tauri-plugin-positioner"
readme = "README.md"
categories = [ "gui", "web-programming" ]
keywords = [ "tauri-plugin" ]

[dependencies]
tauri = { version = "1.0.0-beta.8", features = [ "api-all" ] }
serde = "1"
serde_json = "1"
serde_repr = "0.1"

[features]
system-tray = ["tauri/system-tray"]
